#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
  selected=$((find ~/dev /mnt/DATA/dev -mindepth 1 -maxdepth 1 -type d; echo /home/l/.config/nvim; echo /home/l/vimwiki) | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)
session_exists() {
  tmux has-session -t=$selected_name 2> /dev/null
}

if [[ -z $TMUX ]]; then
  # not in tmux
  if ! session_exists; then
    tmux new-session -s $selected_name -c $selected
  else
    tmux attach -t $selected_name
  fi
else
  if ! session_exists; then
    # create detached to prevent nesting
    tmux new-session -ds $selected_name -c $selected
  fi
  tmux switch-client -t $selected_name
fi
