#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
  selected=$((find ~/dev /mnt/DATA/dev -mindepth 1 -maxdepth 1 -type d; echo /home/l/.config/nvim; echo /home/l/vimwiki) | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]]; then
  # not in tmux
  if [[ -z $tmux_running ]]; then
    # not in tmux and it's not running
    tmux new-session -s $selected_name -c $selected
  else
    # not in tmux but it's running
    if ! tmux has-session -t=$selected_name 2> /dev/null; then
      # session not exist
      tmux new-session -s $selected_name -c $selected
    else
      # session exists
      tmux attach -t $selected_name
    fi
  fi
else
  if ! tmux has-session -t=$selected_name 2> /dev/null; then
    # in tmux but session not exist
    tmux new-session -ds $selected_name -c $selected
    tmux switch-client -t $selected_name
  else
    # in tmux but session exists
    tmux switch-client -t $selected_name
  fi
fi



## simplifying
